#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Apr 12, 2019 07:12:30 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global ks
    ks = StringVar()
    global loc
    loc = StringVar()
    global wey
    wey = StringVar()
    global wem
    wem = StringVar()
    global es
    es = StringVar()
    global eq
    eq = StringVar()
    global st
    st = StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import projectgui
    projectgui.vp_start_gui()


